Traceback (most recent call last):
  File "F:\python_programs\debug\script3.py", line 4, in <module>
    raise Exception('this is the error message')
Exception: this is the error message
